// AUTH 
export const LOGIN_USER_REQUEST  =  'LOGIN_USER_REQUEST';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';
// ADD TWEET
export const ADD_TWEET_REQUEST = 'ADD_TWEET_REQUEST';
export const ADD_TWEET_FAILURE = 'ADD_TWEET_FAILURE';
export const ADD_TWEET_SUCCESS = 'ADD_TWEET_SUCCESS';
// USER TWEETS
export const USER_TWEETS_REQUEST = 'USER_TWEETS_REQUEST';
export const USER_TWEETS_FAILURE = 'USER_TWEETS_FAILURE';
export const USER_TWEETS_SUCCESS = 'USER_TWEETS_SUCCESS';

